### ISSUE TITLE
Italics need semantics where appropriate

### ISSUE THREAD

**Issue by robinwhittleton** [tassos/okakura-kakuzo_the-book-of-tea#3]
Have a look at this section of the semantics manual: https://standardebooks.org/contribute/semantics#semantics-inflection

Where possible, we want italics that refer to the name of a thing to have an `epub:type` attribute, probably picked from the standard vocab list: https://standardebooks.org/vocab/1.0

For example, a book title like `<i>Chaking</i>` should be `<i epub:type="se:name.publication.book">Chaking</i>`, and a newspaper like `<i>Spectator</i>` should be `<i epub:type="se:name.publication.newspaper">Spectator</i>` .

**Comment by tassos** [comment]
I addressed this in 5c5612a.

For the `Hachinochi` (chapter 6, line 21), which is apparently a No-dance (a form of theatre in Japan), I added the type `z3998:drama`, as it was the most appropriate I found. Is it okay @robinwhittleton ?

Finally, I have the ideogram `Cha` appearing in chapter 2, line 17. I am italicizing it cause I think it fits better, but I cannot find a proper semantic type. Any suggestion?

**Comment by tassos** [comment]
Also, should I add epub:type semantics to all the names appearing in the book, even if we don't italicize them? E.g. The tea-masters, other authors, city names etc etc...

**Comment by robinwhittleton** [comment]
Ah, OK. The `z3998:drama` markup would indicate that the contents of the tag are actual drama, not the name of a type of drama (i.e. typically they’d have stage directions, actors, dramatis personae, etc). If it was a specific piece we’d give it `se:name.publication.play`, but as it’s just a type of drama and not in MW I’d just use `<i xml:lang="ja">` here.

For _Cha_, first off it’s not in MW surprisingly so let’s add `xml:lang="ja"`. There’s no specific semantic markup for this beyond using the correct 茶, but that’s less readable in general for most English readers. However we’ll also want to italicise and add a lang attribute to the `Tou` that appears later in the sentence for the same reason.

As for your other semantics, no :) Basically, they’re only needed if they’re italicised with a few exceptions.

**Comment by tassos** [comment]
Well, actually `Hachinochi` is the name of a specific piece of No-dance, which is a form of drama. It's like `Ifigenia` is the name of a specific tragedy, which is a form of drama.

I was looking into the `se:name.publication.play` type, but since this was not a publicized play (I think), I hesitated, that's why I chose the `z3998:drama` type.

**Comment by acabal** [comment]
We can use `se:name.publication.play`, that's close enough. `play` is only under `publication` because typically there is printed matter like scripts, or if successful it is printed and distributed a la Wilde, Shakespeare, etc. Robin is correct, `z3998:drama` indicates that the contents of the tag are actual dramatic lines, versus just the name of a play that is a drama. We would use `z3998:drama` as the top level semantic for a complete edition of a Wilde play for example, instead of (or in addition to) `z3998:fiction`.

**Comment by tassos** [comment]
Ok, this was fixed in d7e6bc1 and 468282b
